-- create databases
CREATE DATABASE IF NOT EXISTS `auth`;
CREATE DATABASE IF NOT EXISTS `songs`;
CREATE DATABASE IF NOT EXISTS `users`;
CREATE DATABASE IF NOT EXISTS `metadata`;
CREATE DATABASE IF NOT EXISTS `cover_art`;
